"""add_user_id_to_search_contexts

Revision ID: 6eceb329c0e6
Revises: 20260414_0002
Create Date: 2026-04-21 09:27:32.240353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eceb329c0e6'
down_revision: Union[str, None] = '20260414_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM search_contexts")
    op.add_column('search_contexts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_search_contexts_user_id'), 'search_contexts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'search_contexts', 'users', ['user_id'], ['user_id'])
    op.create_index(op.f('ix_search_results_place_id'), 'search_results', ['place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_results_place_id'), table_name='search_results')
    op.drop_constraint(None, 'search_contexts', type_='foreignkey')
    op.drop_index(op.f('ix_search_contexts_user_id'), table_name='search_contexts')
    op.drop_column('search_contexts', 'user_id')
    # ### end Alembic commands ###
